export type TempTypes =
                              'OrderByArg' | 
                                  'Role' | 
                          'PartOfSpeech' | 
                          'StatusMobile' | 
                                  'Word' | 
                                'Entity' | 
                              'Sentence' | 
                                'Phrase' | 
                             'MobileApp' | 
                               'Irrverb' | 
                             'Translate' | 
                                  'User' | 
                      'PartOfSpeechDesc' | 
            'TranslateRelationsResolver' | 
                    'TranslateWordsArgs' | 
          'TranslateDisconnectWordsArgs' | 
               'EntityRelationsResolver' | 
             'EntityDisconnectWordsArgs' | 
                     'EntityPhrasesArgs' | 
                   'EntitySentencesArgs' | 
                       'EntityWordsArgs' | 
           'EntityDisconnectPhrasesArgs' | 
         'EntityDisconnectSentencesArgs' | 
               'PhraseRelationsResolver' | 
          'PhraseDisconnectEntitiesArgs' | 
                    'PhraseEntitiesArgs' | 
                 'UserRelationsResolver' | 
                      'UserEntitiesArgs' | 
                          'UserWordArgs' | 
             'SentenceRelationsResolver' | 
        'SentenceDisconnectEntitiesArgs' | 
                  'SentenceEntitiesArgs' | 
                 'WordRelationsResolver' | 
                     'WordTranslateArgs' | 
            'WordDisconnectEntitiesArgs' | 
           'WordDisconnectTranslateArgs' | 
                      'WordEntitiesArgs' | 
              'IrrverbRelationsResolver' | 
           'DeleteManyMobileAppResolver' | 
             'FindManyMobileAppResolver' | 
               'DeleteMobileAppResolver' | 
           'UpdateManyMobileAppResolver' | 
            'AggregateMobileAppResolver' | 
                 'MobileAppCrudResolver' | 
               'CreateMobileAppResolver' | 
               'UpsertMobileAppResolver' | 
              'FindOneMobileAppResolver' | 
               'UpdateManyMobileAppArgs' | 
                   'DeleteMobileAppArgs' | 
                   'CreateMobileAppArgs' | 
                  'FindOneMobileAppArgs' | 
                   'UpdateMobileAppArgs' | 
                   'UpsertMobileAppArgs' | 
               'DeleteManyMobileAppArgs' | 
                 'FindManyMobileAppArgs' | 
               'UpdateMobileAppResolver' | 
           'DeleteManyTranslateResolver' | 
             'FindManyTranslateResolver' | 
                 'TranslateCrudResolver' | 
               'DeleteTranslateResolver' | 
           'UpdateManyTranslateResolver' | 
            'AggregateTranslateResolver' | 
               'CreateTranslateResolver' | 
               'UpsertTranslateResolver' | 
              'FindOneTranslateResolver' | 
                   'UpsertTranslateArgs' | 
                   'UpdateTranslateArgs' | 
                  'FindOneTranslateArgs' | 
               'DeleteManyTranslateArgs' | 
               'UpdateManyTranslateArgs' | 
                   'DeleteTranslateArgs' | 
                   'CreateTranslateArgs' | 
                 'FindManyTranslateArgs' | 
               'UpdateTranslateResolver' | 
                    'EntityCrudResolver' | 
                  'CreateEntityResolver' | 
               'AggregateEntityResolver' | 
                 'FindOneEntityResolver' | 
                  'UpdateEntityResolver' | 
                'FindManyEntityResolver' | 
              'DeleteManyEntityResolver' | 
              'UpdateManyEntityResolver' | 
                  'UpsertEntityResolver' | 
                  'DeleteEntityResolver' | 
                      'CreateEntityArgs' | 
                      'UpdateEntityArgs' | 
                  'DeleteManyEntityArgs' | 
                     'FindOneEntityArgs' | 
                      'DeleteEntityArgs' | 
                    'FindManyEntityArgs' | 
                      'UpsertEntityArgs' | 
                  'UpdateManyEntityArgs' | 
                  'DeletePhraseResolver' | 
              'UpdateManyPhraseResolver' | 
                  'UpsertPhraseResolver' | 
                    'PhraseCrudResolver' | 
              'DeleteManyPhraseResolver' | 
                  'UpdatePhraseResolver' | 
                 'FindOnePhraseResolver' | 
               'AggregatePhraseResolver' | 
                'FindManyPhraseResolver' | 
                  'CreatePhraseResolver' | 
                      'UpsertPhraseArgs' | 
                    'FindManyPhraseArgs' | 
                  'UpdateManyPhraseArgs' | 
                      'DeletePhraseArgs' | 
                  'DeleteManyPhraseArgs' | 
                     'FindOnePhraseArgs' | 
                      'CreatePhraseArgs' | 
                      'UpdatePhraseArgs' | 
                    'UpdateUserResolver' | 
                    'UpsertUserResolver' | 
                 'AggregateUserResolver' | 
                'UpdateManyUserResolver' | 
                   'FindOneUserResolver' | 
                    'DeleteUserResolver' | 
                    'CreateUserResolver' | 
                  'FindManyUserResolver' | 
                'DeleteManyUserResolver' | 
                        'DeleteUserArgs' | 
                        'CreateUserArgs' | 
                    'DeleteManyUserArgs' | 
                    'UpdateManyUserArgs' | 
                        'UpdateUserArgs' | 
                       'FindOneUserArgs' | 
                        'UpsertUserArgs' | 
                      'FindManyUserArgs' | 
                      'UserCrudResolver' | 
        'DeletePartOfSpeechDescResolver' | 
       'FindOnePartOfSpeechDescResolver' | 
        'CreatePartOfSpeechDescResolver' | 
        'UpsertPartOfSpeechDescResolver' | 
      'FindManyPartOfSpeechDescResolver' | 
    'UpdateManyPartOfSpeechDescResolver' | 
          'PartOfSpeechDescCrudResolver' | 
        'UpdatePartOfSpeechDescResolver' | 
     'AggregatePartOfSpeechDescResolver' | 
            'CreatePartOfSpeechDescArgs' | 
            'UpdatePartOfSpeechDescArgs' | 
        'UpdateManyPartOfSpeechDescArgs' | 
          'FindManyPartOfSpeechDescArgs' | 
            'DeletePartOfSpeechDescArgs' | 
           'FindOnePartOfSpeechDescArgs' | 
        'DeleteManyPartOfSpeechDescArgs' | 
            'UpsertPartOfSpeechDescArgs' | 
    'DeleteManyPartOfSpeechDescResolver' | 
                  'SentenceCrudResolver' | 
            'UpdateManySentenceResolver' | 
            'DeleteManySentenceResolver' | 
                'CreateSentenceResolver' | 
                'DeleteSentenceResolver' | 
               'FindOneSentenceResolver' | 
                'UpsertSentenceResolver' | 
              'FindManySentenceResolver' | 
             'AggregateSentenceResolver' | 
                'UpdateSentenceResolver' | 
                'UpdateManySentenceArgs' | 
                    'UpdateSentenceArgs' | 
                    'UpsertSentenceArgs' | 
                    'DeleteSentenceArgs' | 
                   'FindOneSentenceArgs' | 
                'DeleteManySentenceArgs' | 
                    'CreateSentenceArgs' | 
                  'FindManySentenceArgs' | 
                    'CreateWordResolver' | 
                  'FindManyWordResolver' | 
                      'WordCrudResolver' | 
                'DeleteManyWordResolver' | 
                    'UpsertWordResolver' | 
                    'UpdateWordResolver' | 
                      'FindManyWordArgs' | 
                    'DeleteManyWordArgs' | 
                        'CreateWordArgs' | 
                        'DeleteWordArgs' | 
                        'UpsertWordArgs' | 
                        'UpdateWordArgs' | 
                       'FindOneWordArgs' | 
                    'UpdateManyWordArgs' | 
                 'AggregateWordResolver' | 
                'UpdateManyWordResolver' | 
                   'FindOneWordResolver' | 
                    'DeleteWordResolver' | 
                 'CreateIrrverbResolver' | 
               'FindManyIrrverbResolver' | 
             'DeleteManyIrrverbResolver' | 
                 'DeleteIrrverbResolver' | 
                 'UpsertIrrverbResolver' | 
                 'UpdateIrrverbResolver' | 
                   'IrrverbCrudResolver' | 
                    'FindOneIrrverbArgs' | 
                 'UpdateManyIrrverbArgs' | 
                     'UpdateIrrverbArgs' | 
                 'DeleteManyIrrverbArgs' | 
                   'FindManyIrrverbArgs' | 
                     'UpsertIrrverbArgs' | 
                     'DeleteIrrverbArgs' | 
                     'CreateIrrverbArgs' | 
              'AggregateIrrverbResolver' | 
                'FindOneIrrverbResolver' | 
             'UpdateManyIrrverbResolver' | 
             'AggregatePartOfSpeechDesc' | 
                    'AggregateTranslate' | 
                    'AggregateMobileApp' | 
                     'AggregateSentence' | 
                         'AggregateUser' | 
                       'AggregatePhrase' | 
                      'AggregateIrrverb' | 
                         'AggregateWord' | 
                          'BatchPayload' | 
                       'AggregateEntity' | 
    'AggregatePartOfSpeechDescCountArgs' | 
             'AggregateIrrverbCountArgs' | 
           'AggregateTranslateCountArgs' | 
              'AggregateEntityCountArgs' | 
                'AggregateWordCountArgs' | 
           'AggregateMobileAppCountArgs' | 
              'AggregatePhraseCountArgs' | 
            'AggregateSentenceCountArgs' | 
                'AggregateUserCountArgs' | 
       'SentenceUpdateManyMutationInput' | 
     'EntityUpdateManyWithoutWordsInput' | 
                          'EntityFilter' | 
          'EntityCreateWithoutUserInput' | 
                        'DateTimeFilter' | 
'SentenceCreateManyWithoutDisconnectEntitiesInput' | 
                        'WordWhereInput' | 
    'SentenceCreateWithoutEntitiesInput' | 
      'PhraseCreateWithoutEntitiesInput' | 
'TranslateUpdateWithoutDisconnectWordsDataInput' | 
'TranslateUpdateManyWithoutDisconnectWordsInput' | 
                            'WordFilter' | 
'WordUpsertWithWhereUniqueWithoutTranslateInput' | 
                            'RoleFilter' | 
                   'TranslateWhereInput' | 
    'WordUpdateWithoutEntitiesDataInput' | 
'AnotherUser_firstname_lastname_keyCompoundUniqueInput' | 
'WordCreateManyWithoutDisconnectEntitiesInput' | 
                      'WordOrderByInput' | 
        'WordCreateManyWithoutUserInput' | 
'WordUpdateWithWhereUniqueWithoutDisconnectEntitiesInput' | 
'EntityUpdateWithoutDisconnectWordsDataInput' | 
'EntityUpdateManyWithoutDisconnectWordsInput' | 
'EntityCreateManyWithoutDisconnectSentencesInput' | 
'SentenceCreateWithoutDisconnectEntitiesInput' | 
'EntityUpsertWithWhereUniqueWithoutPhrasesInput' | 
        'UserCreateWithoutEntitiesInput' | 
                    'PhraseOrderByInput' | 
'EntityUpsertWithWhereUniqueWithoutWordsInput' | 
 'EntityCreateManyWithoutSentencesInput' | 
    'IrrverbCreateOneWithoutEntityInput' | 
         'EntityUpdateManyMutationInput' | 
       'IrrverbUpsertWithoutEntityInput' | 
                    'IrrverbUpdateInput' | 
'Unique_title_userIdCompoundUniqueInput' | 
                'PhraseWhereUniqueInput' | 
'PartOfSpeechDescUpdateManyMutationInput' | 
            'UserUpsertWithoutWordInput' | 
           'UserUpdateManyMutationInput' | 
                  'TranslateCreateInput' | 
  'PhraseUpdateManyWithoutEntitiesInput' | 
'WordUpsertWithWhereUniqueWithoutEntitiesInput' | 
             'TranslateScalarWhereInput' | 
                  'WordScalarWhereInput' | 
   'EntityUpdateWithoutIrrverbDataInput' | 
                       'WordUpdateInput' | 
'TranslateCreateWithoutDisconnectWordsInput' | 
'WordUpsertWithWhereUniqueWithoutUserInput' | 
'EntityUpdateWithWhereUniqueWithoutUserInput' | 
              'SentenceScalarWhereInput' | 
    'WordUpdateManyWithoutEntitiesInput' | 
     'EntityUpdateWithoutWordsDataInput' | 
'TranslateUpdateWithWhereUniqueWithoutWordsInput' | 
'UserUpdateOneRequiredWithoutEntitiesInput' | 
'EntityUpsertWithWhereUniqueWithoutDisconnectSentencesInput' | 
'SentenceUpsertWithWhereUniqueWithoutEntitiesInput' | 
'SentenceCreateManyWithoutEntitiesInput' | 
'SentenceUpdateManyWithoutDisconnectEntitiesInput' | 
'WordUpsertWithWhereUniqueWithoutDisconnectTranslateInput' | 
'SentenceUpdateWithoutDisconnectEntitiesDataInput' | 
      'EntityUpdateManyWithoutUserInput' | 
                'EntityScalarWhereInput' | 
                     'PhraseCreateInput' | 
                    'EntityOrderByInput' | 
                          'StringFilter' | 
'WordUpdateWithoutDisconnectEntitiesDataInput' | 
                  'SentenceOrderByInput' | 
  'PhraseUpdateWithoutEntitiesDataInput' | 
'EntityUpdateManyWithoutDisconnectPhrasesInput' | 
'WordUpdateManyWithoutDisconnectEntitiesInput' | 
            'WordCreateWithoutUserInput' | 
      'MobileAppUpdateManyMutationInput' | 
'TranslateUpsertWithWhereUniqueWithoutWordsInput' | 
'SentenceUpdateWithWhereUniqueWithoutEntitiesInput' | 
    'EntityCreateOneWithoutIrrverbInput' | 
       'EntityUpsertWithoutIrrverbInput' | 
      'EntityCreateManyWithoutUserInput' | 
                   'SentenceUpdateInput' | 
'PhraseCreateWithoutDisconnectEntitiesInput' | 
                     'EntityCreateInput' | 
'WordUpdateWithoutDisconnectTranslateDataInput' | 
                 'TranslateOrderByInput' | 
         'PhraseUpdateManyMutationInput' | 
                        'UserWhereInput' | 
               'IrrverbWhereUniqueInput' | 
   'IrrverbUpdateWithoutEntityDataInput' | 
'WordUpdateWithWhereUniqueWithoutEntitiesInput' | 
 'EntityUpdateManyWithoutSentencesInput' | 
    'WordUpdateManyWithWhereNestedInput' | 
                      'PhraseWhereInput' | 
                    'PartOfSpeechFilter' | 
'EntityUpdateWithWhereUniqueWithoutDisconnectPhrasesInput' | 
                  'MobileAppUpdateInput' | 
'EntityCreateWithoutDisconnectWordsInput' | 
     'UserCreateOneWithoutEntitiesInput' | 
        'WordUpdateManyWithoutUserInput' | 
    'IrrverbUpdateOneWithoutEntityInput' | 
    'EntityUpdateOneWithoutIrrverbInput' | 
'EntityUpdateManyWithoutDisconnectSentencesInput' | 
                       'UserUpdateInput' | 
'EntityUpsertWithWhereUniqueWithoutSentencesInput' | 
  'PhraseUpdateManyWithWhereNestedInput' | 
'WordCreateWithoutDisconnectTranslateInput' | 
           'PartOfSpeechDescCreateInput' | 
     'EntityCreateManyWithoutWordsInput' | 
'WordUpsertWithWhereUniqueWithoutDisconnectEntitiesInput' | 
'EntityUpdateWithoutDisconnectPhrasesDataInput' | 
       'WordCreateWithoutTranslateInput' | 
      'TranslateUpdateManyMutationInput' | 
                     'IrrverbWhereInput' | 
            'PartOfSpeechDescWhereInput' | 
'EntityCreateWithoutDisconnectSentencesInput' | 
'EntityUpdateWithWhereUniqueWithoutWordsInput' | 
'EntityUpdateWithoutDisconnectSentencesDataInput' | 
 'EntityUpdateWithoutSentencesDataInput' | 
  'TranslateCreateManyWithoutWordsInput' | 
                    'StatusMobileFilter' | 
        'UserUpdateWithoutWordDataInput' | 
             'MobileAppWhereUniqueInput' | 
                   'SentenceCreateInput' | 
   'WordCreateManyWithoutTranslateInput' | 
'PhraseUpdateWithWhereUniqueWithoutDisconnectEntitiesInput' | 
                     'EntityUpdateInput' | 
'PhraseUpdateManyWithoutDisconnectEntitiesInput' | 
   'EntityCreateManyWithoutPhrasesInput' | 
'WordUpdateWithWhereUniqueWithoutTranslateInput' | 
'PhraseUpdateWithoutDisconnectEntitiesDataInput' | 
       'IrrverbCreateWithoutEntityInput' | 
 'UserUpdateOneRequiredWithoutWordInput' | 
               'WordUpdateManyDataInput' | 
       'EntityCreateWithoutPhrasesInput' | 
                 'MobileAppOrderByInput' | 
      'EntityUpdateWithoutUserDataInput' | 
      'PartOfSpeechDescWhereUniqueInput' | 
                    'SentenceWhereInput' | 
                         'BooleanFilter' | 
                  'MobileAppCreateInput' | 
'PhraseCreateManyWithoutDisconnectEntitiesInput' | 
'SentenceUpdateWithWhereUniqueWithoutDisconnectEntitiesInput' | 
          'PartOfSpeechDescOrderByInput' | 
      'TranslateCreateWithoutWordsInput' | 
'PhraseUpsertWithWhereUniqueWithoutEntitiesInput' | 
'WordCreateWithoutDisconnectEntitiesInput' | 
                       'UserCreateInput' | 
           'PartOfSpeechDescUpdateInput' | 
                   'MobileAppWhereInput' | 
'SentenceUpdateManyWithWhereNestedInput' | 
'EntityUpdateWithWhereUniqueWithoutPhrasesInput' | 
                  'UserWhereUniqueInput' | 
                     'NullableIntFilter' | 
             'PhraseUpdateManyDataInput' | 
         'UserCreateOneWithoutWordInput' | 
'EntityUpsertWithWhereUniqueWithoutUserInput' | 
'WordUpdateWithWhereUniqueWithoutUserInput' | 
'WordUpdateManyWithoutDisconnectTranslateInput' | 
  'EntityUpdateManyWithWhereNestedInput' | 
                          'PhraseFilter' | 
'EntityUpsertWithWhereUniqueWithoutDisconnectPhrasesInput' | 
'WordCreateManyWithoutDisconnectTranslateInput' | 
        'WordUpdateWithoutUserDataInput' | 
'SentenceUpsertWithWhereUniqueWithoutDisconnectEntitiesInput' | 
          'TranslateUpdateManyDataInput' | 
'SentenceUpdateManyWithoutEntitiesInput' | 
         'EntityCreateWithoutWordsInput' | 
                'EntityWhereUniqueInput' | 
'EntityCreateWithoutDisconnectPhrasesInput' | 
    'UserUpdateWithoutEntitiesDataInput' | 
       'EntityCreateWithoutIrrverbInput' | 
                             'IntFilter' | 
'TranslateCreateManyWithoutDisconnectWordsInput' | 
                      'UserOrderByInput' | 
'EntityUpsertWithWhereUniqueWithoutDisconnectWordsInput' | 
'TranslateUpsertWithWhereUniqueWithoutDisconnectWordsInput' | 
'TranslateUpdateManyWithWhereNestedInput' | 
              'SentenceWhereUniqueInput' | 
'PhraseUpdateWithWhereUniqueWithoutEntitiesInput' | 
'EntityCreateManyWithoutDisconnectWordsInput' | 
                    'IrrverbCreateInput' | 
           'WordUpdateManyMutationInput' | 
    'WordCreateManyWithoutEntitiesInput' | 
   'EntityUpdateManyWithoutPhrasesInput' | 
   'WordUpdateManyWithoutTranslateInput' | 
  'TranslateUpdateWithoutWordsDataInput' | 
        'IrrverbUpdateManyMutationInput' | 
                  'TranslateUpdateInput' | 
             'TranslateWhereUniqueInput' | 
                  'WordWhereUniqueInput' | 
'EntityUpdateWithWhereUniqueWithoutDisconnectWordsInput' | 
                'PhraseScalarWhereInput' | 
'SentenceUpdateWithoutEntitiesDataInput' | 
'EntityUpdateWithWhereUniqueWithoutDisconnectSentencesInput' | 
             'EntityUpdateManyDataInput' | 
        'WordCreateWithoutEntitiesInput' | 
  'PhraseCreateManyWithoutEntitiesInput' | 
                       'WordCreateInput' | 
           'SentenceUpdateManyDataInput' | 
            'UserCreateWithoutWordInput' | 
   'EntityUpdateWithoutPhrasesDataInput' | 
                       'TranslateFilter' | 
     'EntityCreateWithoutSentencesInput' | 
'EntityUpdateWithWhereUniqueWithoutSentencesInput' | 
                        'SentenceFilter' | 
                     'PhraseUpdateInput' | 
                      'EntityWhereInput' | 
                   'IrrverbOrderByInput' | 
'PhraseUpsertWithWhereUniqueWithoutDisconnectEntitiesInput' | 
  'TranslateUpdateManyWithoutWordsInput' | 
   'WordUpdateWithoutTranslateDataInput' | 
        'UserUpsertWithoutEntitiesInput' | 
'EntityCreateManyWithoutDisconnectPhrasesInput' | 
'TranslateUpdateWithWhereUniqueWithoutDisconnectWordsInput' | 
'WordUpdateWithWhereUniqueWithoutDisconnectTranslateInput';